### ISSUE TITLE
redo file download

### ISSUE THREAD

**Issue by kmpm** [kmpm/nodemcu-uploader#19]
I would like to see a download protocol more similar to the upload one.
And one that does not need to send the same command over and over again until all chunks are sent.

**Comment by lrozema** [comment]
You mean you want to see an upload protocol similar to the download protocol? Because the download protocol is now simply a print, right?

**Comment by kmpm** [comment]
Exactly.... do a loop in lua code that sends chunks of data together with size.
I made a commit (c0bbb7d3446a230011024127226c01e176f7de65) containing, what I think, is the necessary lua code.
It's not tested yet, still fiddling with the python part.

**Comment by kmpm** [comment]
Issue #33 is one of the thinks that can happen without a proper download.
