### ISSUE TITLE
Setting --verbose option causes error

### ISSUE THREAD

**Issue by lorneb** [kmpm/nodemcu-uploader#2]
Traceback (most recent call last):
  File "./upload.py", line 243, in <module>
    logger.setLevel(logging.DEBUG)
NameError: name 'logger' is not defined

**Comment by lorneb** [comment]
Nice useful bit of code thanks.  Is there any way you can test for the existence of the functions needed before re-creating them,  same some time on subsequent uploads?

**Comment by kmpm** [comment]
I have thought about that as well, detecting existing functions, but I don't know how.
I added this as a new issue #4.
