### ISSUE TITLE
Binary file uploads on Windows broken, and a fix.

### ISSUE THREAD

**Issue by hazarkarabay** [kmpm/nodemcu-uploader#23]
This tool capable of doing binary file transfers. But at line 182 I'm seeing that files opening with `t` (text) mode: `open( path, 'rt' )`

This is causing wrong behavior on Windows. The `-v` verify command is also affected. 

For a quick fix, I changed to `open( path, 'rb' )` This fixed it, tested on Windows 7 and Ubuntu 14.04

**Comment by kmpm** [comment]
rb should work everywhere... Can't think of a reason for why I used rt to begin with.
It will be fixed, just not today.
