### ISSUE TITLE
pySerial 3.0 API change

### ISSUE THREAD

**Issue by rahulpowar** [kmpm/nodemcu-uploader#32]
Ran into an issue with a fresh install.

When running with `--baud 115200`, I got an exception `AttributeError: 'Serial' object has no attribute 'setBaudrate'`

Quick search led to this link.

http://stackoverflow.com/questions/34602168/dronekit-failed-to-connect-to-dev-tty-usbmodem1411-serial-object-has-no-at

Downgrading pySerial did work but likely a fix will be needed soon.

**Comment by kmpm** [comment]
* How did you install, using pip or running from a git clone?
* Which platform (win, linux, mac ...)?
* Downgrade to what, pySerial 2.7 I guess?

**Comment by rahulpowar** [comment]
1. Git clone
2. OS-X
3. Yes, 2.7 as noted in the link posted

**Comment by kmpm** [comment]
The solution in https://github.com/mavlink/mavlink/issues/498 seemed as an reasonable workaround.

Please pull the latest master (mainly reorganization) and try again with pySerial 3.0

**Comment by kmpm** [comment]
Havent tested terminal but everything else works in the "next" branch at least

**Comment by kmpm** [comment]
Fixed in df716cc874fc2d56f1867c50a93e714e9b5d7aec
