### ISSUE TITLE
Detect existing functions before adding new ones

### ISSUE THREAD

**Issue by kmpm** [kmpm/nodemcu-uploader#4]
This is to avoid uploading the same functions more than once.
If the protocol is already in place there is not worth spending time doing it again.

But, this is only is any significant speed or memory gain is to be made. Otherwise this issue could be closed.

**Comment by cheloftus** [comment]
I've implemented a pretty basic method for this in my fork (next branch). Hope it helps.

**Comment by kmpm** [comment]
Could you create a pull request?
And if not to much trouble. Do it against master which now contains the changes from next

**Comment by kmpm** [comment]
The patch is working
