### ISSUE TITLE
Terminal does not support alternate baud-rates

### ISSUE THREAD

**Issue by pastukhov** [kmpm/nodemcu-uploader#49]
Looks like --initail_baud otion is ignored and nodemcu-uploder.py stop working since default port speed changed from 9600 to 115200

```
python nodemcu-uploader.py -B 115200 terminal
--- Miniterm on /dev/ttyUSB0: 9600,8,N,1 ---
--- Quit: Ctrl+]  |  Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
����}��u}wu��}wu}u}�����

```

**Comment by kmpm** [comment]
Oh...  Hmm if there were a way to detect the speed.
Den 18 mars 2016 2:25 em skrev "Artem Pastukhov" <notifications@github.com>:
