### ISSUE TITLE
Syntax error after run

### ISSUE THREAD

**Issue by sturchaninov** [kmpm/nodemcu-uploader#52]
When running without arguments from Windows with Python 3.5.1 I see syntax error message:
...ges\nodemcu_uploader\uploader.py", line 348
    print 'buffer size:', len(buffer)
                       ^
SyntaxError: invalid syntax

Seems it happens because of old print function syntax used (print "statement" instead of print("...")) in:
https://github.com/kmpm/nodemcu-uploader/blob/master/nodemcu_uploader/uploader.py#L387
Please fix if I'm right.

**Comment by kmpm** [comment]
Uploader is currently not supported under python 3 and there are
unfortunately no work in progress to support it.

It will happen, but I don't know when.
Den 25 mars 2016 8:07 em skrev "sturchaninov" <notifications@github.com>:

**Comment by kmpm** [comment]
This should be working since version 0.4.3
