### ISSUE TITLE
download does not work

### ISSUE THREAD

**Issue by flyniki** [kmpm/nodemcu-uploader#57]
The code for uploading seems to be missing updates comparing to download code.
In main.py, function operation_download:
please add code like in operation_upload:
    sources, destinations = destination_from_source(sources)
    if len(destinations) == len(sources):
...
In main.py, function destination_from_source
newsources[i] = srcdst[0] might be better replaced by
newsources.append(srcdst[0])

glob.glob(srcdst[0]) returns an empty list, therefore the loop over listing does not work, just 
filename = sources[i]
and omitting the loop seems to work

**Comment by kmpm** [comment]
should be closed by 324ed74f31fe45314b558ef05d55c90f74d11759
