### ISSUE TITLE
nodemcu-uploader running on windows error

### ISSUE THREAD

**Issue by JBSchueler** [kmpm/nodemcu-uploader#69]
I am trying to run nodemcu-uploader on win10 64bit.
My python installation directory is c:\python27
I used github to get the nodemcu-uploader repository

When I try to run I get the following error
![image](https://user-images.githubusercontent.com/7997096/26941917-82a4529e-4c80-11e7-96bd-d75eaeaa6ccd.png)

When I try `setup.py install` it seems ok to me...
![image](https://user-images.githubusercontent.com/7997096/26942021-d397ea26-4c80-11e7-8a5b-d2f6a3df9387.png)

Is it not possible to run nodemcu-uploader on win10?

**Comment by kmpm** [comment]
Strange.
I will look into it.
I have been using Win 10 for most of the time without issues.

Den 8 juni 2017 7:30 em skrev "Ben Schueler" <notifications@github.com>:

**Comment by kmpm** [comment]
Wrapt seems to be a new unintended dependency.... hmm...

**Comment by kmpm** [comment]
Fixed in version 0.4.3.
Closed by d661fac49727825832818754e9779c5bad26f6d9
