### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by kmpm** [kmpm/nodemcu-uploader#90]
Hi,
This project is in need of maintenance and I (kmpm) do not have the time the project deserves.
I really don't use NodeMCU that much any more and am quite busy with other stuff.

If you feel you would like to help out either send me a message or make a comment here.
Would love some help.

**Comment by TerryE** [comment]
@kmpm Peter, maybe you could consider adding me as a committer on the project.  You might know that I am one of the main developers on the NodeMCU project, and keep a cut-down version in date for my own use.  Another option would be for me just to update this master.  Up to you.  Regards Terry

**Comment by kmpm** [comment]
@TerryE, you should have an invite. 
I have no hesitation adding you.

**Comment by kmpm** [comment]
I can publish to pypi, that's not the hard part. But digging up hardware, firmware and triaging bugs is a mess when you have time for it once in a quarter or so. :)
